SELLER_DOVE_COLOR = "#f7b2ad"
BUYER_DOVE_COLOR = "#06d6a0"
STABLE_DOVE_COLOR = "#1098f7"

SELLER_HAWK_COLOR = "#f63c2f"
BUYER_HAWK_COLOR = "#0BA300"
STABLE_HAWK_COLOR = "#024574"

STRATEGIES_COLOR_ARRAY = [SELLER_DOVE_COLOR, BUYER_DOVE_COLOR, STABLE_DOVE_COLOR, SELLER_HAWK_COLOR, BUYER_HAWK_COLOR, STABLE_HAWK_COLOR]